# Launches an ElectrumX server and an Electron Cash SLP wallet in daemon mode.
# The wallet pulls Bitcoin Cash data from the ElectrumX server. The wallet
# also provides a JSON RPC interface for slp.js to talk to, and validate
# SLP token transactions.


electrumx:
  build: electrumx
  dockerfile: Dockerfile
  ports:
    - "50001:50001" # <host port>:<container port>
  volumes:
    - /home/trout/work/bch/electrumx-data:/srv/db
  environment:
      - COIN=BitcoinCashABC
      # Replace "<...>" elements with your own values.
      - DAEMON_URL=http://<rpcuser>:<rpcpass>@<ip>:<port>
  restart: always

electron-cash-slp:
  build: electron-cash-slp
  dockerfile: Dockerfile
  links:
    - electrumx
  ports:
    - "5111:5111"  # <host port>:<container port>
  restart: always
